package com.wy.usashop.mapper;

import com.wy.usashop.pojo.Carshop;
import com.wy.usashop.pojo.CarshopExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CarshopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carshop
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    long countByExample(CarshopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carshop
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    int deleteByExample(CarshopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carshop
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carshop
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    int insert(Carshop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carshop
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    int insertSelective(Carshop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carshop
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    List<Carshop> selectByExample(CarshopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carshop
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    Carshop selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carshop
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    int updateByExampleSelective(@Param("record") Carshop record, @Param("example") CarshopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carshop
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    int updateByExample(@Param("record") Carshop record, @Param("example") CarshopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carshop
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    int updateByPrimaryKeySelective(Carshop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carshop
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    int updateByPrimaryKey(Carshop record);
}