package com.wy.usashop.mapper;

import com.wy.usashop.pojo.Producttype;
import com.wy.usashop.pojo.ProducttypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProducttypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producttype
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    long countByExample(ProducttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producttype
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    int deleteByExample(ProducttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producttype
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    int deleteByPrimaryKey(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producttype
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    int insert(Producttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producttype
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    int insertSelective(Producttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producttype
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    List<Producttype> selectByExample(ProducttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producttype
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    Producttype selectByPrimaryKey(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producttype
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    int updateByExampleSelective(@Param("record") Producttype record, @Param("example") ProducttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producttype
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    int updateByExample(@Param("record") Producttype record, @Param("example") ProducttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producttype
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    int updateByPrimaryKeySelective(Producttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producttype
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    int updateByPrimaryKey(Producttype record);
}