package com.wy.usashop.mapper;

import com.wy.usashop.pojo.Xmorder;
import com.wy.usashop.pojo.XmorderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XmorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmorder
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    long countByExample(XmorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmorder
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    int deleteByExample(XmorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmorder
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    int deleteByPrimaryKey(String oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmorder
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    int insert(Xmorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmorder
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    int insertSelective(Xmorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmorder
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    List<Xmorder> selectByExample(XmorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmorder
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    Xmorder selectByPrimaryKey(String oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmorder
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    int updateByExampleSelective(@Param("record") Xmorder record, @Param("example") XmorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmorder
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    int updateByExample(@Param("record") Xmorder record, @Param("example") XmorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmorder
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    int updateByPrimaryKeySelective(Xmorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmorder
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    int updateByPrimaryKey(Xmorder record);
}