package com.wy.usashop.pojo;

public class Address {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.addressId
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private Integer addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.uid
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.cnee
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private String cnee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.phone
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.ayoubian
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private Integer ayoubian;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.addressId
     *
     * @return the value of address.addressId
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.addressId
     *
     * @param addressId the value for address.addressId
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.uid
     *
     * @return the value of address.uid
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.uid
     *
     * @param uid the value for address.uid
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.cnee
     *
     * @return the value of address.cnee
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public String getCnee() {
        return cnee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.cnee
     *
     * @param cnee the value for address.cnee
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setCnee(String cnee) {
        this.cnee = cnee == null ? null : cnee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.phone
     *
     * @return the value of address.phone
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.phone
     *
     * @param phone the value for address.phone
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address
     *
     * @return the value of address.address
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address
     *
     * @param address the value for address.address
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.ayoubian
     *
     * @return the value of address.ayoubian
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public Integer getAyoubian() {
        return ayoubian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.ayoubian
     *
     * @param ayoubian the value for address.ayoubian
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setAyoubian(Integer ayoubian) {
        this.ayoubian = ayoubian;
    }
}