package com.wy.usashop.pojo;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.aid
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.aname
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private String aname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.apass
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private String apass;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.aid
     *
     * @return the value of admin.aid
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.aid
     *
     * @param aid the value for admin.aid
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.aname
     *
     * @return the value of admin.aname
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public String getAname() {
        return aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.aname
     *
     * @param aname the value for admin.aname
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setAname(String aname) {
        this.aname = aname == null ? null : aname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.apass
     *
     * @return the value of admin.apass
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public String getApass() {
        return apass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.apass
     *
     * @param apass the value for admin.apass
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setApass(String apass) {
        this.apass = apass == null ? null : apass.trim();
    }
}