package com.wy.usashop.pojo;

public class Carshop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carshop.cid
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carshop.uid
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carshop.pid
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carshop.numbers
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private Integer numbers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carshop.allmoney
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private Double allmoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carshop.cid
     *
     * @return the value of carshop.cid
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carshop.cid
     *
     * @param cid the value for carshop.cid
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carshop.uid
     *
     * @return the value of carshop.uid
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carshop.uid
     *
     * @param uid the value for carshop.uid
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carshop.pid
     *
     * @return the value of carshop.pid
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carshop.pid
     *
     * @param pid the value for carshop.pid
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carshop.numbers
     *
     * @return the value of carshop.numbers
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public Integer getNumbers() {
        return numbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carshop.numbers
     *
     * @param numbers the value for carshop.numbers
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setNumbers(Integer numbers) {
        this.numbers = numbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carshop.allmoney
     *
     * @return the value of carshop.allmoney
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public Double getAllmoney() {
        return allmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carshop.allmoney
     *
     * @param allmoney the value for carshop.allmoney
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setAllmoney(Double allmoney) {
        this.allmoney = allmoney;
    }
}