package com.wy.usashop.pojo;

public class Producttype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column producttype.typeid
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column producttype.typeName
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column producttype.typestatus
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private Integer typestatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column producttype.typeid
     *
     * @return the value of producttype.typeid
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column producttype.typeid
     *
     * @param typeid the value for producttype.typeid
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column producttype.typeName
     *
     * @return the value of producttype.typeName
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column producttype.typeName
     *
     * @param typeName the value for producttype.typeName
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column producttype.typestatus
     *
     * @return the value of producttype.typestatus
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public Integer getTypestatus() {
        return typestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column producttype.typestatus
     *
     * @param typestatus the value for producttype.typestatus
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setTypestatus(Integer typestatus) {
        this.typestatus = typestatus;
    }
}