package com.wy.usashop.pojo;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pid
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pname
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.psize
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private String psize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pprice
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private Double pprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pimage
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private String pimage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pnumber
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private Integer pnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.typeid
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private Integer typeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pid
     *
     * @return the value of product.pid
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pid
     *
     * @param pid the value for product.pid
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pname
     *
     * @return the value of product.pname
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pname
     *
     * @param pname the value for product.pname
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.psize
     *
     * @return the value of product.psize
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public String getPsize() {
        return psize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.psize
     *
     * @param psize the value for product.psize
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setPsize(String psize) {
        this.psize = psize == null ? null : psize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pprice
     *
     * @return the value of product.pprice
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public Double getPprice() {
        return pprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pprice
     *
     * @param pprice the value for product.pprice
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setPprice(Double pprice) {
        this.pprice = pprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pimage
     *
     * @return the value of product.pimage
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public String getPimage() {
        return pimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pimage
     *
     * @param pimage the value for product.pimage
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setPimage(String pimage) {
        this.pimage = pimage == null ? null : pimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pnumber
     *
     * @return the value of product.pnumber
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public Integer getPnumber() {
        return pnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pnumber
     *
     * @param pnumber the value for product.pnumber
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setPnumber(Integer pnumber) {
        this.pnumber = pnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.typeid
     *
     * @return the value of product.typeid
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.typeid
     *
     * @param typeid the value for product.typeid
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }
}