package com.wy.usashop.pojo;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.uid
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.uname
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.upass
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private String upass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.ustatus
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private Integer ustatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.ulevel
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private Integer ulevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.score
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.uemil
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    private String uemil;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.uid
     *
     * @return the value of users.uid
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.uid
     *
     * @param uid the value for users.uid
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.uname
     *
     * @return the value of users.uname
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.uname
     *
     * @param uname the value for users.uname
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.upass
     *
     * @return the value of users.upass
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public String getUpass() {
        return upass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.upass
     *
     * @param upass the value for users.upass
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setUpass(String upass) {
        this.upass = upass == null ? null : upass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.ustatus
     *
     * @return the value of users.ustatus
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public Integer getUstatus() {
        return ustatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.ustatus
     *
     * @param ustatus the value for users.ustatus
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setUstatus(Integer ustatus) {
        this.ustatus = ustatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.ulevel
     *
     * @return the value of users.ulevel
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public Integer getUlevel() {
        return ulevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.ulevel
     *
     * @param ulevel the value for users.ulevel
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setUlevel(Integer ulevel) {
        this.ulevel = ulevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.score
     *
     * @return the value of users.score
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.score
     *
     * @param score the value for users.score
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.uemil
     *
     * @return the value of users.uemil
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public String getUemil() {
        return uemil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.uemil
     *
     * @param uemil the value for users.uemil
     *
     * @mbg.generated Wed Apr 29 15:36:29 CST 2020
     */
    public void setUemil(String uemil) {
        this.uemil = uemil == null ? null : uemil.trim();
    }
}